language: python
python:
  - "3.4"
notifications:
  email: false

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy pandas matplotlib scikit-learn
  - conda install --yes -c dan_blanchard python-coveralls
  - conda install --yes seaborn

install:
  - python setup.py install

script:
  - nosetests --with-coverage --cover-package=mclearn
after_success:
  - coveralls
