language: python
python:
  - "3.4"
virtualenv:
  - system_site_packages: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-numpy python-scipy
  - pip install coveralls
# command to install dependencies
install:
  - "pip install -q -e ."
# command to run tests
script:
  - nosetests
after_success:
  - coveralls
